version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  db: # 서비스 명
    image: postgres:13.3 # 사용할 이미지
    container_name: postgres-13 # 컨테이너 이름 설정
    ports:
      - "5432:5432" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      POSTGRES_PASSWORD: "bizmyhand"  # MYSQL 패스워드 설정 옵션
    volumes:
      - /Users/jsk/docker/postgres:/var/lib/postgres/data # -v 옵션 (다렉토리 마운트 설정)